name: Jest Tests Workflow

on:
  push:
    branches:
      - master

jobs:
  Test_Suite:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: Dev
          POSTGRES_DB: ChitChat_test
          POSTGRES_PASSWORD: test pass
          POSTGRES_HOST: localhost
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install deps
        run: yarn --frozen-lockfile
      - name: Run Tests
        run: yarn test
        env:
          CI: true
          POSTGRES_USER: Dev
          POSTGRES_DB: ChitChat_test
          POSTGRES_PASSWORD: test pass
          POSTGRES_HOST: localhost
